version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.9
    working_directory: /home/circleci/pktcapsule
    steps:
      - checkout

      - run:
          name: Run unit tests
          command: go test -v ./...

  golint:
    docker:
      - image: circleci/golang:1.9
    working_directory: /home/circleci/pktcapsule
    steps:
      - checkout

      - run:
          name: Install golint
          command: go get -u golang.org/x/lint/golint

      - run:
          name: Lint
          command: golint -set_exit_status ./...

workflows:
  version: 2
  lint_and_test:
    jobs:
      - build
      - golint
